language: node_js
node_js: '8'

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  # Runnning Linters
  - npm run lint
  # Runnning Unit Test
  - npm run test
  # Runnning Build
  - npm run build

after_script:
  - npm install -g codecov
  - codecov

deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  verbose: true
  on:
    branch: master
